import fs from "node:fs/promises";import path from "node:path";import crypto from "node:crypto";
const scrypt=(v,s)=>new Promise((r,j)=>crypto.scrypt(v,s,64,(e,k)=>e?j(e):r(k))),norm=v=>v.trim().toLowerCase().replace(/\s+/g," ");
async function hash(v){const salt=crypto.randomBytes(16).toString("hex");return{salt,hash:(await scrypt(v,salt)).toString("hex")};}
async function match(v,s,h){const a=Buffer.from(h,"hex"),b=Buffer.from(await scrypt(v,s));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
export class MemberStore{
constructor(file=process.env.ESN_MEMBER_DATA_FILE||"/tmp/esn-members.json"){this.file=file;}
async load(){try{return JSON.parse(await fs.readFile(this.file,"utf8"));}catch(e){if(e.code==="ENOENT")return{members:[]};throw e;}}
async save(d){await fs.mkdir(path.dirname(this.file),{recursive:true});const t=this.file+".tmp";await fs.writeFile(t,JSON.stringify(d,null,2),{mode:0o600});await fs.rename(t,this.file);}
async register({email,password,name,securityQuestion,securityAnswer}){const d=await this.load(),e=email.trim().toLowerCase();if(d.members.some(x=>x.email===e))throw Object.assign(new Error("An account already exists for that email"),{status:409});const p=await hash(password),a=await hash(norm(securityAnswer));const m={memberId:"esn_"+crypto.randomUUID(),email:e,name:name.trim(),passwordHash:p.hash,passwordSalt:p.salt,securityQuestion:securityQuestion.trim(),securityAnswerHash:a.hash,securityAnswerSalt:a.salt,role:"member",credits:0,sessionVersion:1,createdAt:new Date().toISOString()};d.members.push(m);await this.save(d);return m;}
async authenticate({email,password}){const d=await this.load(),m=d.members.find(x=>x.email===email.trim().toLowerCase()&&x.passwordHash);return m&&await match(password,m.passwordSalt,m.passwordHash)?m:null;}
async getSecurityQuestion(email){const d=await this.load(),m=d.members.find(x=>x.email===email.trim().toLowerCase()&&x.securityQuestion);return m?{question:m.securityQuestion}:null;}
async resetWithSecurityAnswer({email,securityAnswer,newPassword}){const d=await this.load(),m=d.members.find(x=>x.email===email.trim().toLowerCase()&&x.securityAnswerHash);if(!m||!await match(norm(securityAnswer),m.securityAnswerSalt,m.securityAnswerHash))return null;const p=await hash(newPassword);m.passwordHash=p.hash;m.passwordSalt=p.salt;m.sessionVersion=(m.sessionVersion||1)+1;await this.save(d);return m;}
async ensureAdmin(email){if(!email)return;const d=await this.load(),e=email.trim().toLowerCase(),m=d.members.find(x=>x.email===e);if(m&&m.role!=="admin"){m.role="admin";m.sessionVersion=(m.sessionVersion||1)+1;await this.save(d);}}
async getById(id){return(await this.load()).members.find(x=>x.memberId===id)||null;}
async listSafe(){return(await this.load()).members.map(({memberId,email,name,role="member",credits=0,createdAt})=>({memberId,email,name,role,credits,createdAt}));}
async updateProfile(id,{name}){const d=await this.load(),m=d.members.find(x=>x.memberId===id);if(!m)return null;if(typeof name==="string"&&name.trim().length>=2&&name.trim().length<=50)m.name=name.trim();else throw Object.assign(new Error("Display name must be 2-50 characters"),{status:400});await this.save(d);return m;}
async setRole(id,role){if(!["member","admin"].includes(role))throw Object.assign(new Error("Invalid role"),{status:400});const d=await this.load(),m=d.members.find(x=>x.memberId===id);if(!m)return null;m.role=role;m.sessionVersion=(m.sessionVersion||1)+1;await this.save(d);return m;}
async setCredits(id,credits){if(!Number.isSafeInteger(credits)||credits<0||credits>1000000000)throw Object.assign(new Error("Invalid credit balance"),{status:400});const d=await this.load(),m=d.members.find(x=>x.memberId===id);if(!m)return null;m.credits=credits;await this.save(d);return m;}
}