import http from "node:http";import {GoogleAuthService}from"./services/googleAuth.js";import{MemberStore}from"./services/memberStore.js";import{issueSession,verifySession}from"./services/sessionTokens.js";
const port=Number(process.env.PORT||8080),audience=process.env.GOOGLE_WEB_CLIENT_ID||"",adminEmail=(process.env.ESN_ADMIN_EMAIL||"").trim().toLowerCase(),google=new GoogleAuthService(audience),members=new MemberStore(process.env.ESN_MEMBER_DATA_FILE);const json=(r,s,b)=>{r.writeHead(s,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"});r.end(JSON.stringify(b));};async function body(q){const c=[];let n=0;for await(const x of q){n+=x.length;if(n>16384)throw Object.assign(new Error("Request too large"),{status:413});c.push(x);}try{return JSON.parse(Buffer.concat(c).toString()||"{}");}catch{throw Object.assign(new Error("Invalid JSON"),{status:400});}}const email=x=>typeof x==="string"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)&&x.length<=254,pw=x=>typeof x==="string"&&x.length>=10&&x.length<=128;
async function auth(q){const s=verifySession((q.headers.authorization||"").replace(/^Bearer\s+/i,""));if(!s)return null;const m=await members.getById(s.sub);return m&&(m.sessionVersion||1)===s.ver?m:null;}
const server=http.createServer(async(q,r)=>{try{if(q.method==="GET"&&q.url==="/health")return json(r,200,{ok:true,service:"esn-hub-backend"});
if(q.method==="POST"&&q.url==="/v1/auth/register"){const b=await body(q);if(!email(b.email)||!pw(b.password)||typeof b.name!=="string"||b.name.trim().length<2||typeof b.securityQuestion!=="string"||b.securityQuestion.trim().length<8||typeof b.securityAnswer!=="string"||b.securityAnswer.trim().length<3)return json(r,400,{error:"Invalid account details"});const m=await members.register(b);if(m.email===adminEmail)await members.ensureAdmin(m.email);const u=await members.getById(m.memberId);return json(r,201,{memberId:u.memberId,name:u.name,email:u.email,role:u.role,sessionToken:issueSession(u)});}
if(q.method==="POST"&&q.url==="/v1/auth/login"){const b=await body(q),m=email(b.email)&&typeof b.password==="string"?await members.authenticate(b):null;if(!m)return json(r,401,{error:"Invalid credentials"});if(m.email===adminEmail)await members.ensureAdmin(m.email);const u=await members.getById(m.memberId);return json(r,200,{memberId:u.memberId,name:u.name,email:u.email,role:u.role||"member",sessionToken:issueSession(u)});}
if(q.method==="POST"&&q.url==="/v1/auth/recovery-question"){const b=await body(q),x=email(b.email)?await members.getSecurityQuestion(b.email):null;return x?json(r,200,x):json(r,404,{error:"Account recovery is unavailable"});}
if(q.method==="POST"&&q.url==="/v1/auth/reset-password"){const b=await body(q);if(!email(b.email)||!pw(b.newPassword)||typeof b.securityAnswer!=="string")return json(r,400,{error:"Invalid reset request"});const m=await members.resetWithSecurityAnswer(b);return m?json(r,200,{message:"Password reset successful"}):json(r,401,{error:"Recovery answer did not match"});}
if(q.method==="GET"&&q.url==="/v1/auth/session"){const m=await auth(q);return m?json(r,200,{memberId:m.memberId,email:m.email,name:m.name,role:m.role||"member"}):json(r,401,{error:"Invalid session"});}
if(q.method==="GET"&&q.url==="/v1/admin/members"){const m=await auth(q);if(!m||m.role!=="admin")return json(r,403,{error:"Admin access required"});return json(r,200,{members:await members.listSafe()});}
return json(r,404,{error:"Not found"});}catch(e){const s=Number(e.status)||500;return json(r,s,{error:s>=500?"Server error":e.message});}});server.listen(port,"0.0.0.0",()=>console.log("ESN Hub backend listening on "+port));