import http from "node:http";import {GoogleAuthService} from "./services/googleAuth.js";import {MemberStore} from "./services/memberStore.js";import {issueSession,verifySession} from "./services/sessionTokens.js";
const port=Number(process.env.PORT||8080),audience=process.env.GOOGLE_WEB_CLIENT_ID||"",google=new GoogleAuthService(audience),members=new MemberStore(process.env.ESN_MEMBER_DATA_FILE);
function json(r,s,b){r.writeHead(s,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"});r.end(JSON.stringify(b));}
async function body(q){const c=[];let n=0;for await(const x of q){n+=x.length;if(n>16384)throw Object.assign(new Error("Request too large"),{status:413});c.push(x);}try{return JSON.parse(Buffer.concat(c).toString()||"{}");}catch{throw Object.assign(new Error("Invalid JSON"),{status:400});}}
const email=x=>typeof x==="string"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)&&x.length<=254,pw=x=>typeof x==="string"&&x.length>=10&&x.length<=128;
const server=http.createServer(async(q,r)=>{try{
if(q.method==="GET"&&q.url==="/health")return json(r,200,{ok:true,service:"esn-hub-backend"});
if(q.method==="POST"&&q.url==="/v1/auth/register"){const b=await body(q);if(!email(b.email)||!pw(b.password)||typeof b.name!=="string"||b.name.trim().length<2||b.name.length>50||typeof b.securityQuestion!=="string"||b.securityQuestion.trim().length<8||b.securityQuestion.length>120||typeof b.securityAnswer!=="string"||b.securityAnswer.trim().length<3||b.securityAnswer.length>120)return json(r,400,{error:"Invalid account details"});const m=await members.register(b);return json(r,201,{memberId:m.memberId,name:m.name,email:m.email,sessionToken:issueSession(m)});}
if(q.method==="POST"&&q.url==="/v1/auth/login"){const b=await body(q),m=email(b.email)&&typeof b.password==="string"?await members.authenticate(b):null;if(!m)return json(r,401,{error:"Invalid credentials"});return json(r,200,{memberId:m.memberId,name:m.name,email:m.email,sessionToken:issueSession(m)});}
if(q.method==="POST"&&q.url==="/v1/auth/recovery-question"){const b=await body(q),x=email(b.email)?await members.getSecurityQuestion(b.email):null;return x?json(r,200,{question:x.question}):json(r,404,{error:"Account recovery is unavailable"});}
if(q.method==="POST"&&q.url==="/v1/auth/reset-password"){const b=await body(q);if(!email(b.email)||!pw(b.newPassword)||typeof b.securityAnswer!=="string")return json(r,400,{error:"Invalid reset request"});const m=await members.resetWithSecurityAnswer(b);if(!m)return json(r,401,{error:"Recovery answer did not match"});return json(r,200,{memberId:m.memberId,message:"Password reset successful"});}
if(q.method==="GET"&&q.url==="/v1/auth/session"){const s=verifySession((q.headers.authorization||"").replace(/^Bearer\s+/i,""));return s?json(r,200,{memberId:s.sub,email:s.email}):json(r,401,{error:"Invalid session"});}
if(q.method==="POST"&&q.url==="/v1/auth/google"){if(!audience)return json(r,503,{error:"Google authentication is not configured"});const b=await body(q),i=await google.verify(b.idToken),m=await members.findOrCreate(i);return json(r,200,{memberId:m.memberId,name:m.name,email:m.email,sessionToken:issueSession(m)});}return json(r,404,{error:"Not found"});
}catch(e){const s=Number(e.status)||500;return json(r,s,{error:s>=500?"Server error":e.message});}});server.listen(port,"0.0.0.0",()=>console.log("ESN Hub backend listening on "+port));